-- filename: .config/nvim/lua/plugins/lsp.lua
-- -- filename: .config/nvim/lua/plugins/lsp.lua
-- local util = require("lspconfig.util")
--
-- -- Helper: true if we're inside a Deno project
-- local function is_deno_root(fname)
--   return util.root_pattern("deno.json", "deno.jsonc")(fname)
-- end
--
-- return {
--   {
--     "neovim/nvim-lspconfig",
--     opts = {
--       servers = {
--         -- DENO: only attach when deno.json(c) exists
--         denols = {
--           root_dir = util.root_pattern("deno.json", "deno.jsonc"),
--           init_options = {
--             lint = true,
--             suggest = {
--               imports = {
--                 hosts = { ["https://deno.land"] = true },
--               },
--             },
--           },
--         },
--
--         -- Prefer VTSLS for TS/JS
--         vtsls = {
--           -- Don't attach if it's a Deno project
--           root_dir = function(fname)
--             if is_deno_root(fname) then
--               return nil
--             end
--             return util.root_pattern("tsconfig.json", "package.json", "jsconfig.json", ".git")(fname)
--           end,
--           single_file_support = true,
--           settings = {
--             typescript = {
--               tsserver = { maxTsServerMemory = 4096 },
--               preferences = {
--                 importModuleSpecifier = "project-relative",
--               },
--             },
--           },
--         },
--
--         -- Disable tsserver to avoid double-binding/conflicts with vtsls
--         tsserver = false,
--       },
--     },
--   },
-- }
