[font]
size = 10.0

[[keyboard.bindings]]
action = "ToggleViMode"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ScrollLineDown"
key = "J"
mode = "Vi"
mods = "Control"

[[keyboard.bindings]]
action = "ScrollLineUp"
key = "K"
mode = "Vi"
mods = "Control"

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "U"
mode = "Vi"
mods = "Control"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "D"
mode = "Vi"
mods = "Control"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mode = "Vi"
mods = "Control"

[[keyboard.bindings]]
action = "ToggleNormalSelection"
key = "V"
mode = "Vi"
mods = "None"

[[keyboard.bindings]]
action = "ToggleLineSelection"
key = "V"
mode = "Vi"
mods = "Shift"

[[keyboard.bindings]]
action = "ToggleBlockSelection"
key = "V"
mode = "Vi"
mods = "Control"

[[keyboard.bindings]]
action = "ClearSelection"
key = "C"
mode = "Vi"
mods = "Shift"

[[keyboard.bindings]]
action = "ClearSelection"
key = "Escape"
mode = "Vi"
mods = "None"

[window.dimensions]
columns = 120
lines = 30
