color = ''
project-name = 'default'
[default]
account_id = 'acct_1QWSK4LIVg5TgGsN'
device_name = 'archDesktop'
display_name = 'Minecraft_Host'
live_mode_api_key = 'rk_live_***********************************************************************************************9561'
live_mode_key_expires_at = '2025-05-31'
live_mode_pub_key = 'pk_live_51QWSK4LIVg5TgGsNdPWv7AJIlprsaeNDUYa5wLXvzXDioRkTqdLDhzNlDdBDlUG5soxHPvRuosNNKJQcCH6ccwhy00rITCyUKu'
test_mode_api_key = 'rk_test_51QWSK4LIVg5TgGsNKJW31Ziv0gYfHzuQ4sFHSEc5BN7T8ltkJYcSL4kjBrGzEK6JA7NGS5Juf5XVS2hoCVzpaQTo00gjHbrIrr'
test_mode_key_expires_at = '2025-05-31'
test_mode_pub_key = 'pk_test_51QWSK4LIVg5TgGsN9atid8AjcRVjMYCAeQxEqSAOH22KxFpGSje5MZxfUTY4RftWzuSfg0w95RH7iDl56V7pywBq00fuA8H2jP'

